int dambyitem(int it);
void weapcom();
void hitplayer(int victim, int wpn);
void killcom();
void bloodrcv(int *array, int isme);
void breakitem(int x);
void wreckdoor();
Boolean testpeace();
void woundmn(int mon, int am);
void fleecom();
void mhitplayer(int mon);
void combatmessage(int, int, int, int);
