void jumpaway();
int exectable(LINE *v);
int getnext();
int getpar();
int prmmod(int p);
int getparnz();
int tables(int v);
void error();
void erreval();
void dostatus();
void dointerrupt();
