int showhelp(char *verb);
void helpcom();
int maxstrength(int p);
int ovalue(int ob);
void valuecom();
void stacom();
void examcom();
void statplyr();
void incom();
void jumpcom();
void wherecom();
void showploc(int a);
