BEGIN {
  print "/*";
  print "**  DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY.";
  print "**  ANY CHANGES YOU MAKE WILL GO AWAY.";
  print "*/";
  print;
  printf "char *Lflags[] =\t{";
  $n = 0;
}

! /^#/ {
  printf("\"%s\",\n\t\t\t ", $0);
  $n = $n + 1;
}

END {
  print "NULL};";
  print;
  printf("#define NUM_LFLAGS %d\n", $n);
}
