/*
**  DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY.
**  ANY CHANGES YOU MAKE WILL GO AWAY.
*/

#define	LFL_Death	0
#define	LFL_NoSummon	3
#define	LFL_NoMobiles	4
#define	LFL_NoMagic	5
#define	LFL_Peaceful	6
#define	LFL_Soundproof	7
#define	LFL_OnePerson	8
#define	LFL_Party	9
#define	LFL_Private	10
#define	LFL_OnWater	11
#define	LFL_InWater	12
#define	LFL_Cold	13
#define	LFL_Outdoors	14
#define	LFL_Dark	15
