/*
**  DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY.
**  ANY CHANGES YOU MAKE WILL GO AWAY.
*/

char *Lflags[] =	{"Death",
			 "",
			 "",
			 "NoSummon",
			 "NoMobiles",
			 "NoMagic",
			 "Peaceful",
			 "Soundproof",
			 "OnePerson",
			 "Party",
			 "Private",
			 "OnWater",
			 "InWater",
			 "Cold",
			 "Outdoors",
			 "Dark",
			 NULL};

#define NUM_LFLAGS 16
