int vichere(int *x);
void sillytp(int per, char *msg);
void new1rcv(int isme, int chan, char *to, char *from, int code, char *text);
void destroy(int ob);
void eat(int ob);
void create(int ob);
int tscale();
int chkdumb();
int chkcrip();
int chksitting();
void wounded(int n);
void resetplayers();
void wearcom();
void removecom();
void setcarrf(int o, int n);
int iswornby(int item, int chr);
void addforce(char *x);
void forchk();
int iam(char *x);
void teletrap(int newch);
void on_flee_event();
void on_flee_mob(int n);
void sitcom();
void standcom();
void dircom();
void treasurecom();
void levelscom();
