void inventory();
void lobjsat(int loc);
void mlobjsat(int x, int m);
void aobjsat(int loc, int mode, int marg);
int unencumbered();
int iscontin(int o1, int o2);
void brkwordw(char *x);
int fobnsys(char *nam, int ctrl, int ct_inf);
int fobn(char *word);
int fobna(char *word);
int fobnin(char *word, int ct);
int fobnc(char *word);
int fobncb(char *word, int by);
int fobnh(char *word);
int getobj();
void getall();
void getallfr();
void dropall();
int ishere(int item);
int iscarrby(int item, int user);
int dropitem();
void dropinpit(int o);
void lisobs();
void lojal2(int n);
void dumpitems();
void dumpstuff(int n, int loc);
void whocom();
void mwhocom();
void whop2(int mode, int st, int end);
void dispuser(int ubase);
void displevel(int n, int s, char* name);
void savelevel(int n, char* title);
void unpack(char *line);
int fpbn(char *name);
int fpbns(char *name);
int alive(int i);
void pnstring(char *s, int a);
int fextern(char *verb);
void lisextern();
void lispeople();
void usercom();
void oplong(int x);
int gotanything(int x);
int findclass(char *n);
int classmatch(int ob, int cl);
