/*
**  DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY.
**  ANY CHANGES YOU MAKE WILL GO AWAY.
*/

char *Oflags[] =	{"Destroyed",
			 "Linked",
			 "Openable",
			 "Lockable",
			 "Pushable",
			 "PushToggle",
			 "Food",
			 "Armour",
			 "Wearable",
			 "Lightable",
			 "Extinguishable",
			 "Key",
			 "GetFlips",
			 "Lit",
			 "Container",
			 "Weapon",
			 "Unlocatable",
			 NULL};

#define NUM_OFLAGS 17
