BEGIN {
  print "/*";
  print "**  DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY.";
  print "**  ANY CHANGES YOU MAKE WILL GO AWAY.";
  print "*/";
  print;
  $n = 0;
}

! /^#/ && ! /^$/ {
  printf("#define\tOFL_%s\t%d\n", $0, $n);
}

! /^#/ {
  $n = $n + 1;
}
