/*
**  DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY.
**  ANY CHANGES YOU MAKE WILL GO AWAY.
*/

#define	OFL_Destroyed	0
#define	OFL_Linked	1
#define	OFL_Openable	2
#define	OFL_Lockable	3
#define	OFL_Pushable	4
#define	OFL_PushToggle	5
#define	OFL_Food	6
#define	OFL_Armour	7
#define	OFL_Wearable	8
#define	OFL_Lightable	9
#define	OFL_Extinguishable	10
#define	OFL_Key	11
#define	OFL_GetFlips	12
#define	OFL_Lit	13
#define	OFL_Container	14
#define	OFL_Weapon	15
#define	OFL_Unlocatable	16
