int contains(char *s1, char *s2);
void pncom();
int gamecom(char *str);
int brkword();
int chklist(char *word, char *lista[], int listb[]);
int Match(char *x, char *y);
int chkverb();
void doaction(int n);
void aliascom();
void gamrcv(int *blok);
void eorte();
void rescom();
void eatcom();
void calibme();
int levelof(int score);
void playcom();
void getreinput(char *blob);
void shoutcom();
void saycom();
void tellcom();
void scorecom();
void exorcom();
void givecom();
void dogive(int ob, int pl);
void stealcom();
void dosumm(int loc);
void updcom();
void becom();
void convcom();
void rawcom();
void rollcom();
void bugcom();
void typocom();
void lookcom();
void unveilcom();
void emptycom();
void unalias();
void unpolymorph();
