/*
**  DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY.
**  ANY CHANGES YOU MAKE WILL GO AWAY.
*/

char *Pflags[] =	{"Female",
			 "Unsummonable",
			 "PflagEdit",
			 "Operator",
			 "NoArms",
			 "Color",
			 "NoSnoop",
			 "NoShout",
			 "Brief",
			 "InvisStart",
			 "Quiet",
			 "Echo",
			 "NoHassle",
			 "Emote",
			 "Possessed",
			 "Aloof",
			 "Blind",
			 "Deaf",
			 "Dumb",
			 "Crippled",
			 "Assassin",
			 "CannotMSG",
			 "ChangeTitle",
			 "NoExorcise",
			 "Glowing",
			 NULL};

#define NUM_PFLAGS 25
