/*
**  DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY.
**  ANY CHANGES YOU MAKE WILL GO AWAY.
*/

#define	PFL_Female	0
#define	PFL_Unsummonable	1
#define	PFL_PflagEdit	2
#define	PFL_Operator	3
#define	PFL_NoArms	4
#define	PFL_Color	5
#define	PFL_NoSnoop	6
#define	PFL_NoShout	7
#define	PFL_Brief	8
#define	PFL_InvisStart	9
#define	PFL_Quiet	10
#define	PFL_Echo	11
#define	PFL_NoHassle	12
#define	PFL_Emote	13
#define	PFL_Possessed	14
#define	PFL_Aloof	15
#define	PFL_Blind	16
#define	PFL_Deaf	17
#define	PFL_Dumb	18
#define	PFL_Crippled	19
#define	PFL_Assassin	20
#define	PFL_CannotMSG	21
#define	PFL_ChangeTitle	22
#define	PFL_NoExorcise	23
#define	PFL_Glowing	24
