void byte_put(int *, int, int);
int byte_fetch(int, int);
int bit_fetch(int, int);
void bit_set(int *, int);
void bit_clear(int *, int);
void setoloc(int, int, int);
int ohany(int);
void setpsex(int, int);
int ptothlp(int);
int willhold(int, int);
void setpfighting(int, int);
int otstmask(int, int);
int isavl(int);
int ospare(int);
char *oname(int);
char *pname(int);
void mudlog(char *format, ...);
void addtolog(char *file, char *format, ...);
