void vcpy(int *dest, int *source, int len);
void mstoout(int *block);
int sendamsg(char *name);
void send2(int *block);
void readamsg(FILE *channel, int *block, int num);
void rte();
int findstart(FILE *unit);
int findend(FILE *unit);
void talker(char *name);
void cleanup(int *inpbk);
int entergame(char *name, char *hname);
void broad(char *mesg);
char split(int *block, char *nam1, char *nam2, char *work, char *luser);
void trapch(int chan);
void putmeon(char *name);
void loseme();
void update();
void revise(int cutoff);
void lookin(int room);
