typedef enum { sunny, rainy, stormy, snowing, blizzard, hailing } weather_type;

void adjust_weather (weather_type);
void set_weather (weather_type);
void longwthr (void);
void wthrrcv (weather_type);
void showwthr (void);
int outdoors (void);
void sillycom (char *);
void posecom (void);
void emotecom (void);
void emotetocom (void);
void echocom (void);
void echoallcom (void);
void echotocom (void);
void praycom (void);
int cancarry (int);
int roomdark (void);
int isdark (void);
int modifwthr (int);
